### PR TITLE
renamed Method to HttpMethod as it causes confusion with an enum in o…

### PR DESCRIPTION
**Pull request by KrisBoonefaes**
…bjc/runtime.h (in projects that use objc)

### CODE REVIEW

**Comment by fousa** [comment]
🎈I would prefer to use `HTTPMethod`.

screenshot 2016-09-19 14 00 07

**Review by doozMen — CHANGES_REQUESTED** [review]
Ik denk ook httpMethod voor var

```
class Call {
   let httpMethod: HttpMethod
...

Alleen wel kleine letters omdat dat sinds swift 3.0 gevraagd wordt.
```

**Comment by fousa** [comment]
Good point.

**Comment by KrisBoonefaes** [comment]
Wait I'm renaming it from Method to HttpMethod because Method exists already and the proposal is to use HTTPMethod instead, which... exists already?

**Comment by fousa** [comment]
It should be `httpMethod` according to the Swift guidelines. And it _"exists"_ as a property under `URLRequest`, so that is not an issue.

**Review by fousa — APPROVED** [review]

**Review by doozMen — APPROVED** [review]

**Pull request merged**
